### PR TITLE
Fix building on Ubuntu 22.10

### PR DESCRIPTION
**Pull request by JorisGoosen**
With this version of the code I can build & run it on both Ubuntu and macOs

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Will test in a bit!

**Comment by eddelbuettel** [comment]
No luck yet (when working off your branch)

```sh
edd@rob:/tmp/rcpp/rinside/rinside/inst/examples/qt/build(master)$ cmake -S ../cmake/ -G "Unix Makefiles"
CMake Error at /usr/share/cmake-3.24/Modules/FindQt4.cmake:1314 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/rcpp/rinside/rinside/inst/examples/qt/build/CMakeFiles/CMakeOutput.log".
edd@rob:/tmp/rcpp/rinside/rinside/inst/examples/qt/build(master)$ 
```

**Comment by JorisGoosen** [comment]
The errormessage sounds rather like you are using an older version of the code as it looks for Qt4 instead of Qt6.
Also in your copy-paste:
> edd@rob:/tmp/rcpp/rinside/rinside/inst/examples/qt/build(master)$
Perhaps the old local `master` is checked out?

**Comment by eddelbuettel** [comment]
Doh. Quite possibly.  Was in a rush. So sorry!

Works perfectly fine (modulo too much compiler noise from Rcpp, whoops) when I am on the correct branch.

**Comment by eddelbuettel** [comment]
To make up for the _whoops_ I allowed myself a rebase and push back to you -- this PR is now cleanly on commit ahead of master.

**Comment by JorisGoosen** [comment]
Thanks for the test and Ill get back to you once I feel up to fighting with Windows again, as I do need to use RInside with Qt there anyway...

**Comment by eddelbuettel** [comment]
As maintainer, I am quite happy to not insist on Windows.  I once or twice ages went through all the hoops to demonstrate it works but Linux and macOS are simply much more important.

So to me the only TODO (on my end) is to add you to ChangeLog and NEWS for the two quick PRs.  Thanks again for both!

**Pull request merged**
