### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ellert**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks for the pull request.  

Can we have a bit of a motivating discussion about why/where you think you need them?

**Comment by ellert** [comment]
I was trying to package R-RInside as an RPM for Fedora. The RPM creation failed because the buildroot path was detected to be present in some of the files being packaged:

```
+ /usr/lib/rpm/check-buildroot
/home/ellert/rpmbuild/BUILDROOT/R-RInside-0.2.13-1.fc23.x86_64/usr/src/debug/R-RInside-0.2.13/RInside/src/RInsideEnvVars.h:        "R_LIBRARY_DIR","/home/ellert/rpmbuild/BUILDROOT/R-RInside-0.2.13-1.fc23.x86_64/usr/lib64/R/library",
/home/ellert/rpmbuild/BUILDROOT/R-RInside-0.2.13-1.fc23.x86_64/usr/src/debug/R-RInside-0.2.13/RInside/src/RInsideEnvVars.h:        "R_LIBS","/home/ellert/rpmbuild/BUILDROOT/R-RInside-0.2.13-1.fc23.x86_64/usr/lib64/R/library",
/home/ellert/rpmbuild/BUILDROOT/R-RInside-0.2.13-1.fc23.x86_64/usr/src/debug/R-RInside-0.2.13/RInside/src/RInsideEnvVars.h:        "R_PACKAGE_DIR","/home/ellert/rpmbuild/BUILDROOT/R-RInside-0.2.13-1.fc23.x86_64/usr/lib64/R/library/RInside",
Binary file /home/ellert/rpmbuild/BUILDROOT/R-RInside-0.2.13-1.fc23.x86_64/usr/lib64/libRInside.so matches
Binary file /home/ellert/rpmbuild/BUILDROOT/R-RInside-0.2.13-1.fc23.x86_64/usr/lib64/R/library/RInside/libs/RInside.so matches
Found '/home/ellert/rpmbuild/BUILDROOT/R-RInside-0.2.13-1.fc23.x86_64' in installed files; aborting
```

By filtering out the variables containing the buildroot path the RPM build succeeds.

The missing LDFLAGS is just missing - some of the expected linker flags are not used.

**Comment by eddelbuettel** [comment]
Ok, thanks for the feedback.  

I looked first at `LDFLAGS` which I had thought was going into `ALL_LIBS` but doesn't so this looks legit -- but we seemingly never needed it over in .deb land.  

As for the other ones I was hesitating because that part has not changed in _forever_ but I'll have enough local tests there to see if run-time behaviour were to be be affected.  If so I'll report back.

**Comment by eddelbuettel** [comment]
All good.  The `wt/` examples needs another update too (now need to link to with `-lboost_system` too).

I'll add you to the `ChangeLog` file with your GH email, ok?

Thanks again for the PR -- appreciate it.

**Pull request merged**
