### PR TITLE
check _WIN32 rather than WIN32

### PR DESCRIPTION
**Pull request by kevinushey**
For new Rtools compatibility.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks mich!

Explain to me again how this did not break before?  Because Rtools used to support both?

**Comment by jonathon-love** [comment]
hi,

this PR isn't enough, it still won't compile with -std=c++11. let me investigate.

looks to me like WIN32 was and is a legit macro, but under -std=c++11 this is no longer the case.

**Comment by jonathon-love** [comment]
oh, ok, it looks like the issue is that the R headers (in 3.2.3 at least) are still using #ifdef WIN32

line 77 here:
http://docs.rexamine.com/R-devel/RStartup_8h_source.html

are you interested in following this up @eddelbuettel ? brian ripley always hurts my feelings.

**Comment by eddelbuettel** [comment]
Hm, why are tossing around URLs to a 3rd party site on friggin' GitHub when there is [wch's well known mirror](https://github.com/wch/r-source)?

As you are the one troubled by this, could you possibly try something with all of

- r-release
- r-devel
- whatever R you can use with Rtools using 4.9.*

Anything else we are missing, @kevinushey ?

**Comment by kevinushey** [comment]
I don't think there's anything else that needs to be done on the RInside side. You could probably just add something like:

```
#ifdef _WIN32
# define WIN32
#endif
```

before including the R headers. That said, I think that `_WIN32` is the 'canonical' way of declaring Windows, although I forget the nuances of when / if / who should define `WIN32` vs. `_WIN32` and so on...

**Comment by eddelbuettel** [comment]
I am pretty I went over this once in the past.  [This site](https://sourceforge.net/p/predef/wiki/OperatingSystems/) was always a good resource, and it has `_WIN32` as the canonical one. The R 3.2.3 source and the R-devel source appear to have both.

**Comment by jonathon-love** [comment]
> Hm, why are tossing around URLs to a 3rd party site on friggin' GitHub when there is wch's well known mirror?

apparently news hadn't made it to my search engine :P

> As you are the one troubled by this, could you possibly try something with all of

looking here, there's still the #ifdef Win32

https://github.com/wch/r-source/blob/trunk/src/include/R_ext/RStartup.h#L35

so i'm pretty sure the issue would persist in r-devel, etc.

**Comment by eddelbuettel** [comment]
And FWIW what is currently in the master branch here just passed fine on win-builder.

**Comment by jonathon-love** [comment]
yup, it's only an issue with `-std=c++11`

**Comment by eddelbuettel** [comment]
I am not sure what your point is. Do you think we need 

```C++
#ifndef WIN32
#ifdef _WIN32
#define WIN32
#endif
#endif
```

It is not our job to make R itself ready for g++ 4.9.* on Windoze.  We look after a particular package here, and it builds _with the tools I have at my disposal_ namely win-builder.  You need to submit easier to understand, and more clearly argued, requests for changes.

**Comment by kevinushey** [comment]
Right, I mean that if @jonathon-love wanted to work around this _locally_ he could use

```
#ifdef _WIN32
# define WIN32
#endif

#include <RInside.h>
```

I don't think there's any more changes to be made on the RInside side; R likely will need to change something to accommodate the new toolchain and C++11.

**Comment by eddelbuettel** [comment]
:+1:

**Comment by eddelbuettel** [comment]
And C++11 is _totally_ uncharted territory _on Windows_ as we have been stuck at g++ 4.6.* for ages.

There is nothing more to say here, unless I miss something.

**Comment by jonathon-love** [comment]
yup, i think this is all rounded off. thanks for that suggestion @kevinushey, i'm going to make use of it.

**Comment by eddelbuettel** [comment]
:+1:

**Pull request merged**
