### PR TITLE
Change cmake to work with Qt6 and remove deprecated code

### PR DESCRIPTION
**Pull request by JorisGoosen**
Should fix https://github.com/eddelbuettel/rinside/issues/53

### CODE REVIEW

**Review by eddelbuettel — CHANGES_REQUESTED** [review]
Lovely stuff.  I don't speak `cmake` all that fluently so I trust you here.  The code change is pretty benign which is awesome too.

One 'pretty-please' for a bit more usage doc.

**Comment by JorisGoosen** [comment]
Ill add the "mkdir build" things to the docs, and as Ive only tested it on mac I ill also give it a spin on windows to see whether it works there.

**Comment by eddelbuettel** [comment]
Maybe don't bother with Windows.  That may be too painful with mingw and all.

**Comment by JorisGoosen** [comment]
Ive added some things to the README as requested.

I did try building on windows for a bit in Qt creator but that did turn out to be too painful for today.
I will get back to it later and if I get it working Ill open a new PR.

This one should already be quite an improvement

**Review by eddelbuettel — APPROVED** [review]
Thanks!

**Comment by eddelbuettel** [comment]
Actually, it does work for me on Ubuntu 22.10:

```sh
edd@rob:~/git/rinside/inst/examples/qt(master)$ git ls | head -1
*   49d5203 - (HEAD -> master, origin/master) Merge pull request #54 from JorisGoosen/fixQtDemo (2 minutes ago) <Dirk Eddelbuettel>
edd@rob:~/git/rinside/inst/examples/qt(master)$ mkdir build && cd build
edd@rob:~/git/rinside/inst/examples/qt/build(master)$ cmake -S ../cmake -G "Unix Makefiles"
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/edd/git/rinside/inst/examples/qt/build/CMakeFiles/CMakeOutput.log".
edd@rob:~/git/rinside/inst/examples/qt/build(master)$ 
```

**Comment by JorisGoosen** [comment]
> But I then have to fight with lto where I can circumvent an error on to end on RInside symbols not being linked. Did you have any of that fun?

I did have some weird issues with the RInside symbols not being linked and then it might help to change:
`execute_process(COMMAND Rscript -e "RInside:::LdFlags()" OUTPUT_VARIABLE RINSIDELIBS)` 
to:
```
execute_process(COMMAND Rscript -e "RInside:::LdFlags()" OUTPUT_VARIABLE RINSIDELIBS)
string(STRIP ${RINSIDELIBS} RINSIDELIBS)
string(REPLACE "\"" "" RINSIDELIBS ${RINSIDELIBS})
```

Im also still trying to get it to build on windows and this was required there.

**Comment by eddelbuettel** [comment]
No change (and I purged build/ to be sure).

**Pull request merged**
