### PR TITLE
Use run_Rmainloop() to resolve MS Windows issues.

### PR DESCRIPTION
**Pull request by djsamperi**
Tested on Windows, Ubuntu, MacOS.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
That looks pretty clean to me -- thanks for putting all that time in to chase the issue.

@kalibera : what is your view?  Can I / should I merge this for RInside or can you forsee reasons not to?  I guess we could also keep the previous setup and use the proposed change on Windows only?

**Comment by kalibera** [comment]
From a cursory look at the documentation (Writing R Extensions), both forms should do the same. The change is to use the simpler form where one doesn't need to run a custom action after processing a line of input. It makes sense to use the simpler form, but then, both should work. If I were you I would ask for an analysis why the original code didn't work, to rule out the option the problems mentioned in the comment weren't actually caused by some still present bug, which just got hidden away by this by coincidence.

**Comment by eddelbuettel** [comment]
From what @djsamperi was saying in several posts to rcpp-devel I gather that the observed outcome does not cleanly reproduce so the proposed change is "likely" and improvement but that is not guaranteed.    As the change is small I lean towards accepting it.

**Comment by djsamperi** [comment]
The comment at the top of R_ReplDLLdo1() suggests that there are known problems with this function that need addressing, and in my experience, small issues on the Linux side tend to become larger issues on the Windows side: it provides a more sensitive test. The early termination does not happen with simple computations, only with plotting, so these may trigger timing or sync issues. Finally, there are a number of Windows-only callbacks that do not do anything. Perhaps some kind of handshake is required, but this is just a guess.

**Comment by eddelbuettel** [comment]
Thanks again.  A 'heuristic' change was good enough for us in the past; some "Heisenbugs" do not come around often enough.  I think I'll run with this and look into a CRAN update 'soon'.

**Comment by eddelbuettel** [comment]
Thanks again. This is now on CRAN as part of version 0.2.18.

**Pull request merged**
